# Generated by Django 2.1.4 on 2019-01-01 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('salutation', models.CharField(choices=[('Mr', 'Mister'), ('Mis', 'Misses'), ('Dr', 'Doctor'), ('Er', 'Engineer'), ('Prof', 'Professor')], max_length=30)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('birtday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('authar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
