# Generated by Django 2.1.4 on 2019-01-05 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='authar',
            new_name='author',
        ),
    ]
