# Generated by Django 2.1.4 on 2019-01-05 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_person_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
