# Generated by Django 2.1.4 on 2019-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_person_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.CharField(max_length=800),
        ),
    ]
