# Generated by Django 2.1.4 on 2019-01-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190105_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birtday',
            new_name='birthday',
        ),
    ]
